name: project_mid
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Fixed the lints version

flutter:
  uses-material-design: true

  assets:
    - assets/ps5.jpg
    - assets/xbox.jpg
    - assets/macbook.jpg
    - assets/iphone.jpg
    - assets/samsung.jpg
    - assets/apple_watch.jpg
    - assets/electronics.jpg
